ipAddr: localhost
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kkmall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 66CcFf!!

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: kkmall-order
  session:
    store-type: redis
  redis:
    host: ${ipAddr}
    port: 6379
    password: linkekun
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: true
    suffix: .html
    prefix: classpath:/templates/

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000

kkmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10