ipAddr: localhost
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kkmall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 66CcFf!!

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: kkmall-order
  session:
    store-type: redis
  redis:
    host: ${ipAddr}
    port: 6379
    password: linkekun

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000