spring:
  application:
    name: kkmall-third-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: mall-kk
      access-key: LTAI5tCHtotRisgLvCsp5pv5
      secret-key: zWiSQOcz5faTSkropwNssB7rqgMYmV
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5
server:
  port: 30000
