spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: http://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://kkmall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: coupon_route
          uri: lb://kkmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: member_route
          uri: lb://kkmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: ware_route
          uri: lb://kkmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        #  OSS签名的转发
        - id: third-server_route
          uri: lb://kkmall-third-server
          predicates:
            - Path=/api/third/server/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

#过滤器要放最下面才不会被替换路径/api/*路径
        - id: admin_route
          uri: lb://kkmall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
        - id: kkmall_search_route
          uri: lb://kkmall-search
          predicates:
            - Host=search.kkmall.com
        - id: kkmall_auth_route
          uri: lb://kkmall-auth-server
          predicates:
            - Host=auth.kkmall.com
        - id: kkmall_seckill_route
          uri: lb://kkmall-seckill
          predicates:
            - Host=seckill.kkmall.com
        - id: kkmall_cart_route
          uri: lb://kkmall-cart
          predicates:
            - Host=cart.kkmall.com
        - id: kkmall_member_route
          uri: lb://kkmall-member
          predicates:
            - Host=member.kkmall.com
        - id: kkmall_order_route
          uri: lb://kkmall-order
          predicates:
            - Host=order.kkmall.com  
        # 任何以kkmall.com结尾的域名转发到kkmall-product
        # 注意！！！Nginx代理给网关的时候，会丢失请求Host
        - id: kkmall_host_route
          uri: lb://kkmall-product
          predicates:
            - Host=**.kkmall.com,kkmall.com,item.kkmall.com
  application:
    name: kkmall-gateway
server:
  port: 88
