server:
  port: 12000
spring:
  application:
    name: kkmall-search
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719


logging:
  level:
    name.lkk.kkmall: debug